version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:     
      - db
    
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drc_challenge